"use client";

import { useEffect, useMemo, useState } from "react";
import Papa from "papaparse";

type Campaign = { name:string; objective:string; spend:number; results:number; cost:number; clicks:number; impressions:number; ctr:number; frequency:number; status:string };
type Draft = { summary:string; changes:string[]; spotlightTitle:string; spotlight:string[]; recommendations:{priority:string;title:string;body:string}[]; plan:{action:string;priority:string;impact:string}[]; internal:{title:string;items:string[]}[] };
type Account = { id:string; name:string; location:string; reportMonth:string; dateRange:string; logoDataUrl:string; logoUrl?:string; campaigns:Campaign[]; draft:Draft };
type PendingImport = { campaigns:Campaign[]; reportMonth:string; dateRange:string };

const pcwdCampaigns:Campaign[]=[
  {name:"Retargeting",objective:"Website contacts",spend:301.78,results:39,cost:7.7379,clicks:1385,impressions:9789,ctr:13.4743,frequency:2.576,status:"Paused"},
  {name:"Broad",objective:"Prospecting",spend:158.15,results:0,cost:0,clicks:316,impressions:6886,ctr:6.201,frequency:2.775,status:"Active"},
  {name:"Brand Story Video Views",objective:"ThruPlay",spend:140.88,results:20583,cost:.00684,clicks:90,impressions:42754,ctr:4.7808,frequency:1.081,status:"Paused"},
  {name:"Retargeting - Lead Gen",objective:"Lead generation",spend:3.58,results:0,cost:0,clicks:2,impressions:193,ctr:1.554,frequency:1.177,status:"Active"},
];
const defaultDraft:Draft={
  summary:"July generated 39 tracked website contacts at a $7.74 cost per contact. Retargeting produced all recorded contact conversions, while the Brand Story campaign added 20,583 completed video views at a highly efficient cost. The next priority is turning that engagement into a stronger conversion path.",
  changes:["Restructured the campaign architecture. Separated broad prospecting, video awareness, engagement retargeting, and lead-generation activity so each stage can be evaluated clearly.","Built stronger warm-audience coverage. Prepared the account to retarget video viewers and engaged users instead of relying only on general website activity.","Reviewed conversion delivery and tracking. Identified that website contacts are concentrated in retargeting while the Broad campaign has no tracked result type in the export.","Launched a dedicated retargeting lead campaign. The new campaign began July 31 and needs more delivery time before performance conclusions can be made."],
  spotlightTitle:"RETARGETING IS THE CURRENT CONVERSION ENGINE",
  spotlight:["39 website contacts came from the engagement retargeting campaign.","The campaign produced contacts at a $7.74 cost per result from $301.78 in spend.","The Brand Story campaign generated 20,583 ThruPlays for $140.88, creating a sizeable pool of warm viewers.","The Broad campaign drove 316 link clicks, but the export shows no recorded result type, making conversion tracking a priority.","The lead-generation retargeting campaign launched on July 31 and should be evaluated after it receives sufficient delivery."],
  recommendations:[{priority:"HIGH PRIORITY",title:"Verify the full conversion path",body:"Confirm that form submissions, calls, and booked appointments are captured consistently so Meta's contact count can be compared with lead quality."},{priority:"HIGH PRIORITY",title:"Activate warm video audiences",body:"Use high-intent video viewers and engaged users in retargeting to turn the month's awareness volume into measurable inquiries."},{priority:"MEDIUM PRIORITY",title:"Give lead gen time to learn",body:"Keep the new campaign stable long enough to collect meaningful delivery before making budget or creative decisions."}],
  plan:[{action:"Validate website contact and call tracking",priority:"High",impact:"Reliable CPL and lead-quality reporting"},{action:"Add video-viewer and engagement retargeting audiences",priority:"High",impact:"More qualified warm traffic"},{action:"Review prospecting landing-page conversion",priority:"High",impact:"Turn existing clicks into inquiries"},{action:"Monitor the new lead-generation campaign",priority:"Medium",impact:"Establish a reliable CPL baseline"},{action:"Sequence testimonials and installation videos",priority:"Medium",impact:"Stronger progression from awareness to action"}],
  internal:[{title:"Tracking flags",items:["Confirm which Meta result types count as qualified leads.","Reconcile Meta results against the CRM or client lead log."]},{title:"Client questions",items:["How many leads were qualified?","How many booked appointments or estimates?","Which services and locations produced the best leads?"]},{title:"AM talking points",items:["Separate awareness results from conversion results.","Discuss lead quality alongside CPL."]},{title:"Missing for next report",items:["Previous-month comparison export","Qualified lead, booking, and sales counts","Ad-level creative export"]}],
};
const initial:Account={id:"pcwd",name:"Polk County Window & Door",location:"Lakeland, Florida",reportMonth:"July 2026",dateRange:"July 1 - July 31, 2026",logoDataUrl:"/pcwd-logo.png",logoUrl:"",campaigns:pcwdCampaigns,draft:defaultDraft};
const clone=<T,>(v:T):T=>JSON.parse(JSON.stringify(v));
const money=(v:number,d=2)=>v?`$${v.toLocaleString("en-US",{minimumFractionDigits:d,maximumFractionDigits:d})}`:"-";
const num=(v:number)=>v.toLocaleString("en-US",{maximumFractionDigits:0});
const isLead=(s:string)=>/(lead|contact|form|call|appointment|conversion)/i.test(s)&&!/(thruplay|video|view|reach|click|impression)/i.test(s);
const isVideo=(s:string)=>/(thruplay|video view)/i.test(s);

function calc(campaigns:Campaign[]){
  const spend=campaigns.reduce((a,c)=>a+c.spend,0),impressions=campaigns.reduce((a,c)=>a+c.impressions,0),clicks=campaigns.reduce((a,c)=>a+c.clicks,0);
  const leadRows=campaigns.filter(c=>isLead(c.objective)),leads=leadRows.reduce((a,c)=>a+c.results,0),leadSpend=leadRows.filter(c=>c.results>0).reduce((a,c)=>a+c.spend,0);
  const videoViews=campaigns.filter(c=>isVideo(c.objective)).reduce((a,c)=>a+c.results,0);
  return {spend,impressions,clicks,leads,cpl:leads?leadSpend/leads:0,videoViews,cpc:clicks?spend/clicks:0,linkRate:impressions?clicks/impressions*100:0,frequency:impressions?campaigns.reduce((a,c)=>a+c.frequency*c.impressions,0)/impressions:0};
}
async function assetDataUrl(src:string){if(src.startsWith("data:"))return src;const b=await fetch(src).then(r=>r.blob());return await new Promise<string>((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>resolve(String(fr.result));fr.onerror=reject;fr.readAsDataURL(b)});}
function csvCampaigns(rows:Record<string,string>[]):Campaign[]{return rows.filter(r=>r["Campaign name"]).map(r=>({name:r["Campaign name"],objective:r["Result type"]||"No tracked result",spend:Number(r["Amount spent (USD)"]||0),results:Number(r.Results||0),cost:Number(r["Cost per result"]||0),clicks:Number(r["Link clicks"]||0),impressions:Number(r.Impressions||0),ctr:Number(r["CTR (all)"]||0),frequency:Number(r.Frequency||0),status:(r["Delivery status"]||"").includes("active")?"Active":"Paused"}))}
function freshDraft(name:string,month:string,m:{leads:number;cpl:number;spend:number;videoViews:number}):Draft{return {...clone(defaultDraft),summary:`${month} performance for ${name} generated ${num(m.leads)} tracked leads or contacts at ${money(m.cpl)} per result from ${money(m.spend)} in total Meta spend.${m.videoViews?` Video campaigns also generated ${num(m.videoViews)} completed views.`:""} Review lead quality and campaign-level performance before finalizing next month's plan.`,changes:["Add the campaign and account changes completed during this reporting period.","Document targeting, creative, budget, tracking, or landing-page updates.","Add any launches, pauses, tests, or optimizations that the client should know about."],spotlightTitle:"KEY RESULTS FROM THIS PERIOD",spotlight:[`${num(m.leads)} tracked leads or contacts were recorded during the period.`,`Total Meta spend was ${money(m.spend)} with a ${money(m.cpl)} blended cost per tracked lead or contact.`,m.videoViews?`${num(m.videoViews)} completed video views helped build warmer audiences.`:"Add the strongest campaign or creative result here.","Add context about lead quality, bookings, sales, or CRM outcomes here."],recommendations:clone(defaultDraft.recommendations),plan:clone(defaultDraft.plan),internal:clone(defaultDraft.internal)};}

function Field({value,onChange,label,one=false}:{value:string;onChange:(v:string)=>void;label:string;one?:boolean}){return one?<input className="edit-field" aria-label={label} value={value} onChange={e=>onChange(e.target.value)}/>:<textarea className="edit-field" aria-label={label} value={value} onChange={e=>onChange(e.target.value)}/>}
function Metric({label,value,detail,primary=false}:{label:string;value:string;detail:string;primary?:boolean}){return <article className={primary?"metric primary":"metric"}><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>}

export default function Home(){
  const [accounts,setAccounts]=useState<Account[]>([clone(initial)]),[activeId,setActiveId]=useState("pcwd"),[editing,setEditing]=useState(false),[view,setView]=useState<"client"|"internal">("client"),[showSetup,setShowSetup]=useState(true),[agencyLogo,setAgencyLogo]=useState("/apex-logo-cropped.png"),[ready,setReady]=useState(false),[pendingImport,setPendingImport]=useState<PendingImport|null>(null),[logoLoading,setLogoLoading]=useState(false),[logoError,setLogoError]=useState("");
  const account=accounts.find(a=>a.id===activeId)||accounts[0],metrics=useMemo(()=>calc(account.campaigns),[account.campaigns]);
  useEffect(()=>{const raw=localStorage.getItem("apex-report-accounts-v1")||localStorage.getItem("msp-report-accounts-v1");if(raw)try{const saved=JSON.parse(raw);if(saved.length){setAccounts(saved);localStorage.setItem("apex-report-accounts-v1",raw)}}catch{};Promise.all([assetDataUrl("/apex-logo-cropped.png"),assetDataUrl(account.logoDataUrl)]).then(([agency,client])=>{setAgencyLogo(agency);setAccounts(cur=>cur.map(a=>a.id===account.id?{...a,logoDataUrl:client}:a));setReady(true)});},[]);
  const persist=(next:Account[])=>{setAccounts(next);localStorage.setItem("apex-report-accounts-v1",JSON.stringify(next))};
  const patchAccount=(patch:Partial<Account>)=>persist(accounts.map(a=>a.id===activeId?{...a,...patch}:a));
  const patchDraft=(draft:Draft)=>patchAccount({draft});
  async function logoUpload(file?:File){if(!file)return;const data=await new Promise<string>((res,rej)=>{const fr=new FileReader();fr.onload=()=>res(String(fr.result));fr.onerror=rej;fr.readAsDataURL(file)});patchAccount({logoDataUrl:data,logoUrl:""});setLogoError("");}
  async function logoFromUrl(){const url=(account.logoUrl||"").trim();if(!url){setLogoError("Enter a public image URL first.");return}setLogoLoading(true);setLogoError("");try{const response=await fetch("/api/logo-from-url",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url})});const json=await response.json();if(!response.ok||!json.dataUrl)throw new Error(json.error||"Unable to load that logo URL.");patchAccount({logoDataUrl:json.dataUrl,logoUrl:url});}catch(error){setLogoError(error instanceof Error?error.message:"Unable to load that logo URL.")}finally{setLogoLoading(false)}}
  function csvUpload(file?:File){if(!file)return;Papa.parse<Record<string,string>>(file,{header:true,skipEmptyLines:true,complete:r=>{const campaigns=csvCampaigns(r.data);if(!campaigns.length){alert("This CSV does not contain Meta Ads campaign fields.");return}const first=r.data[0],month=first["Reporting starts"]?new Date(`${first["Reporting starts"]}T00:00:00`).toLocaleDateString("en-US",{month:"long",year:"numeric"}):account.reportMonth,dateRange=first["Reporting starts"]&&first["Reporting ends"]?`${first["Reporting starts"]} - ${first["Reporting ends"]}`:account.dateRange;setPendingImport({campaigns,reportMonth:month,dateRange});}})}
  function generateReport(){const source=pendingImport,campaigns=source?.campaigns??account.campaigns;if(!campaigns.length){alert("Upload a Meta Ads CSV before generating the report.");return}if(!source&&!confirm("Regenerate this report? This will replace the current generated narrative. Campaign data and account details will be preserved."))return;const month=source?.reportMonth??account.reportMonth,dateRange=source?.dateRange??account.dateRange,m=calc(campaigns);patchAccount({campaigns,reportMonth:month,dateRange,draft:freshDraft(account.name,month,m)});setPendingImport(null);setEditing(false);setShowSetup(false);}
  function addAccount(){const id=`account-${Date.now()}`,name="New APEX Account",base:Account={id,name,location:"City, State",reportMonth:"Reporting Month",dateRange:"Reporting date range",logoDataUrl:"",logoUrl:"",campaigns:[],draft:freshDraft(name,"This month",{leads:0,cpl:0,spend:0,videoViews:0})};persist([...accounts,base]);setActiveId(id);setPendingImport(null);setShowSetup(true);setEditing(true)}
  function removeAccount(){if(accounts.length===1||!confirm(`Delete ${account.name} from this device?`))return;const next=accounts.filter(a=>a.id!==activeId);persist(next);setActiveId(next[0].id)}
  const d=account.draft;
  const setList=(key:"changes"|"spotlight",i:number,v:string)=>patchDraft({...d,[key]:d[key].map((x,n)=>n===i?v:x)});
  const payload=JSON.stringify({account,metrics,agencyLogo,view});
  return <main className="generator-app">
    <header className="generator-top"><div className="top-brand"><img src="/apex-logo-cropped.png" alt="APEX"/><div><b>APEX</b><span>Meta Reporting Generator</span></div></div><div className="top-actions"><button className="download" type="button" onClick={generateReport} disabled={!pendingImport&&!account.campaigns.length} title={!pendingImport&&!account.campaigns.length?"Upload a Meta Ads CSV to generate this report":undefined}>{pendingImport||!account.campaigns.length?"Generate Report":"Regenerate Report"}</button><div className="segmented"><button className={view==="client"?"active":""} onClick={()=>setView("client")}>Client report</button><button className={view==="internal"?"active":""} onClick={()=>setView("internal")}>AM view</button></div><button className={editing?"edit-toggle editing":"edit-toggle"} onClick={()=>setEditing(!editing)}>{editing?"Finish editing":"Edit narrative"}</button><button className="download pdf-download" type="button" disabled={!ready||!account.logoDataUrl} onClick={()=>window.print()} title="Open the print dialog and choose Save as PDF">{ready?"Download PDF":"Preparing logos..."}</button><form method="POST" action="/api/export"><input type="hidden" name="payload" value={payload}/><button className="download" disabled={!ready||!account.logoDataUrl} type="submit">{ready?"Download Word":"Preparing logos..."}</button></form></div></header>
    <div className="generator-layout">
      <aside className="account-panel"><div className="panel-heading"><span>Accounts</span><button onClick={addAccount}>+ New</button></div><div className="account-list">{accounts.map(a=><button key={a.id} className={a.id===activeId?"selected":""} onClick={()=>{setActiveId(a.id);setPendingImport(null);setShowSetup(true)}}><span>{a.logoDataUrl?<img src={a.logoDataUrl} alt=""/>:<i>{a.name.charAt(0)}</i>}</span><b>{a.name}</b></button>)}</div><div className="account-tools"><button onClick={()=>setShowSetup(!showSetup)}>{showSetup?"Hide account setup":"Account setup"}</button><button className="danger" onClick={removeAccount}>Delete account</button></div>{showSetup&&<div className="setup-card"><label>Account name<input value={account.name} onChange={e=>patchAccount({name:e.target.value})}/></label><label>Location<input value={account.location} onChange={e=>patchAccount({location:e.target.value})}/></label><label>Report month<input value={account.reportMonth} onChange={e=>patchAccount({reportMonth:e.target.value})}/></label><label>Date range<input value={account.dateRange} onChange={e=>patchAccount({dateRange:e.target.value})}/></label><label className="upload-label">Client logo file<input type="file" accept="image/png,image/jpeg" onChange={e=>logoUpload(e.target.files?.[0])}/><span>{account.logoDataUrl?"Replace logo file":"Upload logo file"}</span></label><div className="logo-url-field"><label>Or use logo URL<input type="url" placeholder="https://example.com/logo.png" value={account.logoUrl||""} onChange={e=>patchAccount({logoUrl:e.target.value})} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();logoFromUrl()}}}/></label><button type="button" onClick={logoFromUrl} disabled={logoLoading}>{logoLoading?"Loading...":"Use logo URL"}</button>{logoError&&<small className="logo-error">{logoError}</small>}</div><label className="upload-label primary-upload">Meta Ads CSV<input type="file" accept=".csv,text/csv" onChange={e=>csvUpload(e.target.files?.[0])}/><span>{pendingImport?"Replace monthly export":"Upload monthly export"}</span></label>{pendingImport?<small>CSV ready: {pendingImport.campaigns.length} campaign rows for {pendingImport.reportMonth}.</small>:<small>Upload an ad set-level Meta export, then click Generate Report. KPIs and narrative will be calculated from the file.</small>}<button className="download" type="button" onClick={generateReport} disabled={!pendingImport} title={!pendingImport?"Upload a Meta Ads CSV first":undefined}>Generate Report</button></div>}</aside>
      <div className="report-workspace">{editing&&<div className="edit-banner"><b>Edit mode is on.</b> Narrative changes save automatically for this account.</div>}<div className={editing?"report-shell is-editing":"report-shell"}>
        <header className="report-header">{account.logoDataUrl?<img className="client-logo" src={account.logoDataUrl} alt={account.name}/>:<div className="logo-placeholder">UPLOAD CLIENT LOGO</div>}<div><b>META ADS REPORT</b><span>{account.dateRange.toUpperCase()}</span></div></header>
        <section className="hero"><p className="eyebrow">Monthly performance report · {account.location}</p><h1>{account.name}</h1>{editing?<Field label="Executive summary" value={d.summary} onChange={v=>patchDraft({...d,summary:v})}/>:<div className="summary">{d.summary}</div>}</section>
        <section><h2>Primary KPIs</h2><div className="metrics three"><Metric primary label="Leads / contacts" value={num(metrics.leads)} detail="Tracked by Meta"/><Metric primary label="Cost per lead" value={money(metrics.cpl)} detail="Lead-producing campaigns"/><Metric primary label="Total spend" value={money(metrics.spend)} detail={`${account.campaigns.length} campaign rows`}/></div></section>
        <section><h2>Secondary KPIs</h2><div className="metrics five"><Metric label="Impressions" value={num(metrics.impressions)} detail="Total delivery"/><Metric label="Link clicks" value={num(metrics.clicks)} detail={`${metrics.linkRate.toFixed(2)}% link click rate`}/><Metric label="Cost per link click" value={money(metrics.cpc)} detail="Blended"/><Metric label="Video results" value={num(metrics.videoViews)} detail="ThruPlays / video views"/><Metric label="Avg. frequency" value={metrics.frequency.toFixed(2)} detail="Weighted"/></div></section>
        <section><div className="section-title"><h2>Campaign breakdown</h2><span>Meta export · Ad set level</span></div><div className="table-wrap"><table><thead><tr><th>Campaign</th><th>Result type</th><th>Spend</th><th>Results</th><th>Cost / result</th><th>Link clicks</th><th>CTR (all)</th></tr></thead><tbody>{account.campaigns.map((c,i)=><tr key={`${c.name}-${i}`}><td><b>{c.name}</b><small>{c.status}</small></td><td>{c.objective}</td><td>{money(c.spend)}</td><td>{c.results?num(c.results):"-"}</td><td>{money(c.cost,c.cost<1?3:2)}</td><td>{num(c.clicks)}</td><td>{c.ctr.toFixed(2)}%</td></tr>)}</tbody><tfoot><tr><td colSpan={2}>Total</td><td>{money(metrics.spend)}</td><td>{num(metrics.leads)} leads</td><td>{money(metrics.cpl)}</td><td>{num(metrics.clicks)}</td><td>-</td></tr></tfoot></table></div></section>
        <section className="page-break"><div className="page-heading"><div><p>{account.name.toUpperCase()}</p><h2>Changes Made This Period</h2></div><span>{account.reportMonth.toUpperCase()}</span></div><h3>What changed and why it matters</h3><div className="change-list">{d.changes.map((x,i)=><article key={i}><span>{i+1}</span>{editing?<Field label={`Change ${i+1}`} value={x} onChange={v=>setList("changes",i,v)}/>:<p>{x}</p>}</article>)}</div><h3>Results spotlight</h3><div className="spotlight">{editing?<Field one label="Spotlight title" value={d.spotlightTitle} onChange={v=>patchDraft({...d,spotlightTitle:v})}/>:<h4>{d.spotlightTitle}</h4>}<ul>{d.spotlight.map((x,i)=><li key={i}>{editing?<Field label={`Spotlight ${i+1}`} value={x} onChange={v=>setList("spotlight",i,v)}/>:x}</li>)}</ul></div></section>
        <section className="page-break"><div className="page-heading"><div><p>{account.name.toUpperCase()}</p><h2>Suggestions & Next Steps</h2></div><span>{account.reportMonth.toUpperCase()}</span></div><h3>Suggestions for next period</h3><div className="recommendations">{d.recommendations.map((r,i)=><article key={i}>{editing?<><Field one label={`Recommendation ${i+1} priority`} value={r.priority} onChange={v=>patchDraft({...d,recommendations:d.recommendations.map((x,n)=>n===i?{...x,priority:v}:x)})}/><Field one label={`Recommendation ${i+1} title`} value={r.title} onChange={v=>patchDraft({...d,recommendations:d.recommendations.map((x,n)=>n===i?{...x,title:v}:x)})}/><Field label={`Recommendation ${i+1}`} value={r.body} onChange={v=>patchDraft({...d,recommendations:d.recommendations.map((x,n)=>n===i?{...x,body:v}:x)})}/></>:<><span>{r.priority}</span><h4>{r.title}</h4><p>{r.body}</p></>}</article>)}</div><h3>Next period plan</h3><div className="plan-table"><div className="plan-head"><b>Action item</b><b>Priority</b><b>Expected impact</b></div>{d.plan.map((r,i)=><div className="plan-row" key={i}>{editing?<><Field one label={`Plan ${i+1} action`} value={r.action} onChange={v=>patchDraft({...d,plan:d.plan.map((x,n)=>n===i?{...x,action:v}:x)})}/><Field one label={`Plan ${i+1} priority`} value={r.priority} onChange={v=>patchDraft({...d,plan:d.plan.map((x,n)=>n===i?{...x,priority:v}:x)})}/><Field one label={`Plan ${i+1} impact`} value={r.impact} onChange={v=>patchDraft({...d,plan:d.plan.map((x,n)=>n===i?{...x,impact:v}:x)})}/></>:<><b>{r.action}</b><span>{r.priority}</span><span>{r.impact}</span></>}</div>)}</div></section>
        {view==="internal"&&<section className="internal page-break"><div className="page-heading"><div><p>ACCOUNT MANAGEMENT ONLY</p><h2>Internal Notes & Follow-Up</h2></div><span>{account.reportMonth.toUpperCase()}</span></div><div className="internal-grid">{d.internal.map((s,si)=><article key={si}><h3>{s.title}</h3><ul>{s.items.map((x,ii)=><li key={ii}>{editing?<Field label={`${s.title} ${ii+1}`} value={x} onChange={v=>patchDraft({...d,internal:d.internal.map((z,n)=>n===si?{...z,items:z.items.map((q,k)=>k===ii?v:q)}:z)})}/>:x}</li>)}</ul></article>)}</div></section>}
        <footer><img src="/apex-logo-cropped.png" alt="APEX"/><span>Prepared for {account.name} · {account.reportMonth}</span></footer>
      </div></div>
    </div>
  </main>
}
