import { AlignmentType, BorderStyle, Document, Footer, HeadingLevel, ImageRun, PageBreak, Packer, Paragraph, ShadingType, Table, TableCell, TableRow, TextRun, WidthType } from "docx";

export const runtime = "nodejs";

type Campaign={name:string;objective:string;spend:number;results:number;cost:number;clicks:number;impressions:number;ctr:number;frequency:number;status:string};
type Draft={summary:string;changes:string[];spotlightTitle:string;spotlight:string[];recommendations:{priority:string;title:string;body:string}[];plan:{action:string;priority:string;impact:string}[];internal:{title:string;items:string[]}[]};
type Payload={account:{name:string;location:string;reportMonth:string;dateRange:string;logoDataUrl:string;campaigns:Campaign[];draft:Draft};metrics:{spend:number;impressions:number;clicks:number;leads:number;cpl:number;videoViews:number;cpc:number;linkRate:number;frequency:number};agencyLogo:string;view:string};
const green="58BD3B",pale="EDF7E9",gray="727272";
const money=(v:number,d=2)=>v?`$${v.toLocaleString("en-US",{minimumFractionDigits:d,maximumFractionDigits:d})}`:"-";
const num=(v:number)=>v.toLocaleString("en-US",{maximumFractionDigits:0});
function imageData(dataUrl:string){if(!dataUrl?.startsWith("data:"))return null;const [head,b64]=dataUrl.split(",",2),raw=atob(b64),data=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)data[i]=raw.charCodeAt(i);return {data,type:head.includes("jpeg")?"jpg":"png" as "png"|"jpg"};}
const cell=(text:string,bold=false,fill?:string)=>new TableCell({shading:fill?{fill,type:ShadingType.CLEAR}:undefined,margins:{top:100,bottom:100,left:110,right:110},children:[new Paragraph({children:[new TextRun({text,bold,size:18,font:"Arial",color:fill===green?"FFFFFF":"171717"})]})]});
const label=(text:string)=>new Paragraph({spacing:{before:180,after:100},children:[new TextRun({text:text.toUpperCase(),bold:true,color:gray,characterSpacing:25,size:18,font:"Arial"})]});
const bullet=(text:string)=>new Paragraph({text,bullet:{level:0},spacing:{after:90},style:"Normal"});
const pageTitle=(text:string)=>new Paragraph({heading:HeadingLevel.HEADING_1,spacing:{before:120,after:150},border:{bottom:{color:green,style:BorderStyle.SINGLE,size:18,space:8}},children:[new TextRun({text,bold:true,color:"171717",size:34,font:"Arial"})]});

export async function POST(request:Request){
  const form=await request.formData(),p=JSON.parse(String(form.get("payload"))) as Payload,a=p.account,d=a.draft,m=p.metrics,client=imageData(a.logoDataUrl),agency=imageData(p.agencyLogo);
  const headerCells=[new TableCell({width:{size:50,type:WidthType.PERCENTAGE},borders:{top:{style:BorderStyle.NONE},bottom:{style:BorderStyle.NONE},left:{style:BorderStyle.NONE},right:{style:BorderStyle.NONE}},children:[new Paragraph({children:client?[new ImageRun({data:client.data,type:client.type,transformation:{width:210,height:62}})]:[new TextRun({text:a.name,bold:true,size:22,font:"Arial"})]})]}),new TableCell({width:{size:50,type:WidthType.PERCENTAGE},borders:{top:{style:BorderStyle.NONE},bottom:{style:BorderStyle.NONE},left:{style:BorderStyle.NONE},right:{style:BorderStyle.NONE}},children:[new Paragraph({alignment:AlignmentType.RIGHT,children:[new TextRun({text:"META ADS REPORT",bold:true,color:gray,size:22,font:"Arial"}),new TextRun({text:`\n${a.dateRange.toUpperCase()}`,color:"999999",size:17,font:"Arial"})]})]})];
  const children:(Paragraph|Table)[]=[
    new Table({width:{size:100,type:WidthType.PERCENTAGE},borders:{top:{style:BorderStyle.NONE},bottom:{style:BorderStyle.NONE},left:{style:BorderStyle.NONE},right:{style:BorderStyle.NONE},insideHorizontal:{style:BorderStyle.NONE},insideVertical:{style:BorderStyle.NONE}},rows:[new TableRow({children:headerCells})]}),
    new Paragraph({spacing:{before:100,after:30},children:[new TextRun({text:a.name,bold:true,size:38,font:"Arial"})]}),
    new Paragraph({spacing:{after:90},children:[new TextRun({text:`Monthly performance report · ${a.location}`,color:gray,size:18,font:"Arial"})]}),
    new Paragraph({shading:{fill:pale,type:ShadingType.CLEAR},border:{left:{color:green,style:BorderStyle.SINGLE,size:20,space:10}},spacing:{before:60,after:180},indent:{left:160,right:160},children:[new TextRun({text:d.summary,size:21,font:"Arial"})]}),
    label("Primary KPIs"),new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:[new TableRow({children:[cell(`LEADS / CONTACTS\n${num(m.leads)}\nTracked by Meta`,true,pale),cell(`COST PER LEAD\n${money(m.cpl)}\nLead campaigns`,true,pale),cell(`TOTAL SPEND\n${money(m.spend)}\n${a.campaigns.length} campaign rows`,true,pale)]})]}),
    label("Secondary KPIs"),new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:[new TableRow({children:[cell(`Impressions\n${num(m.impressions)}`),cell(`Link clicks\n${num(m.clicks)}`),cell(`Cost/link click\n${money(m.cpc)}`),cell(`Video results\n${num(m.videoViews)}`),cell(`Frequency\n${m.frequency.toFixed(2)}`)]})]}),
    label("Campaign breakdown"),new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:[new TableRow({tableHeader:true,children:[cell("Campaign",true,green),cell("Result type",true,green),cell("Spend",true,green),cell("Results",true,green),cell("Cost/result",true,green)]}),...a.campaigns.map(c=>new TableRow({children:[cell(c.name,true),cell(c.objective),cell(money(c.spend)),cell(c.results?num(c.results):"-"),cell(money(c.cost,c.cost<1?3:2))]}))]}),
    new Paragraph({children:[new PageBreak()]}),pageTitle("Changes Made This Period"),label("What changed and why it matters"),...d.changes.map(x=>new Paragraph({numbering:{reference:"changes",level:0},spacing:{after:110},children:[new TextRun({text:x,size:21,font:"Arial"})]})),label("Results spotlight"),new Paragraph({shading:{fill:pale,type:ShadingType.CLEAR},spacing:{before:60,after:80},children:[new TextRun({text:d.spotlightTitle,bold:true,color:"2F7628",size:22,font:"Arial"})]}),...d.spotlight.map(bullet),
    new Paragraph({children:[new PageBreak()]}),pageTitle("Suggestions & Next Steps"),label("Suggestions for next period"),...d.recommendations.flatMap(r=>[new Paragraph({spacing:{before:100,after:40},children:[new TextRun({text:r.priority,bold:true,color:r.priority.includes("HIGH")?"B86E12":"2F7628",size:17,font:"Arial"})]}),new Paragraph({spacing:{after:40},children:[new TextRun({text:r.title,bold:true,size:24,font:"Arial"})]}),new Paragraph({spacing:{after:100},children:[new TextRun({text:r.body,size:20,font:"Arial"})]})]),label("Next period plan"),new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:[new TableRow({tableHeader:true,children:[cell("Action item",true,green),cell("Priority",true,green),cell("Expected impact",true,green)]}),...d.plan.map(r=>new TableRow({children:[cell(r.action,true),cell(r.priority),cell(r.impact)]}))]}),
  ];
  if(p.view==="internal")children.push(new Paragraph({children:[new PageBreak()]}),pageTitle("Internal Notes & Follow-Up"),...d.internal.flatMap(s=>[label(s.title),...s.items.map(bullet)]));
  const footerChildren=[new Paragraph({alignment:AlignmentType.LEFT,children:agency?[new ImageRun({data:agency.data,type:agency.type,transformation:{width:72,height:20}})]:[]}),new Paragraph({alignment:AlignmentType.RIGHT,children:[new TextRun({text:`Prepared for ${a.name} · ${a.reportMonth}`,color:"999999",size:15,font:"Arial"})]})];
  const doc=new Document({numbering:{config:[{reference:"changes",levels:[{level:0,format:"decimal",text:"%1",alignment:AlignmentType.LEFT,style:{paragraph:{indent:{left:400,hanging:220}}}}]}]},styles:{default:{document:{run:{font:"Arial",size:20},paragraph:{spacing:{line:270}}}}},sections:[{properties:{page:{margin:{top:650,right:650,bottom:650,left:650}}},footers:{default:new Footer({children:footerChildren})},children}]});
  const blob=await Packer.toBlob(doc),safe=a.name.replace(/[^a-z0-9]+/gi,"_").replace(/^_|_$/g,"");
  return new Response(blob,{headers:{"Content-Type":"application/vnd.openxmlformats-officedocument.wordprocessingml.document","Content-Disposition":`attachment; filename="${safe}_${a.reportMonth.replace(/\s+/g,"_")}_Meta_Report${p.view==="internal"?"_AM":""}.docx"`}});
}
